#!/bin/bash


if [ $1=="-p" ]; then
    #runs pytest and check if failed
    pytest &     
    git add .
    git commit -m "$2"
    #You can trade the $2 to match your repo so you dont have to 
    #always type the name of your repo and branch
    git push $3
else
    #runs pytest and check if failed
    if pytest | grep -q 'failed in '; then
        echo "Error on test"
    else
        #checkout 
        git add .
        git commit -m "$1"
        #You can trade the $2 to match your repo so you dont have to 
        #always type the name of your repo and branch
        git push $2
    fi
fi
